version: "3.8"

networks:
    artemiz:

services:
    artemiz_site:
        env_file:
            - .env
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${DOCKER_UID:-1000}
                - GID=${DOCKER_GID:-1000}
        container_name: artemiz-nginx
        ports:
            - ${DOCKER_NGINX_PORT}:80
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - artemiz_php
        networks:
            - artemiz

    artemiz_php:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./dockerfiles/php.dockerfile
            args:
                - UID=${DOCKER_UID:-1000}
                - GID=${DOCKER_GID:-1000}
        container_name: artemiz-php
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - artemiz

    artemiz_composer:
        env_file:
            - .env
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
            args:
                - UID=${DOCKER_UID:-1000}
                - GID=${DOCKER_GID:-1000}
        container_name: composer
        volumes:
            - ./:/var/www/html:delegated
        working_dir: /var/www/html
        depends_on:
            - artemiz_php
        user: laravel
        entrypoint: ["composer", "--ignore-platform-reqs"]
        networks:
            - artemiz

    artemiz_artisan:
        env_file:
            - .env
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${DOCKER_UID:-1000}
                - GID=${DOCKER_GID:-1000}
        container_name: artisan
        volumes:
            - ./:/var/www/html:delegated
        working_dir: /var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - artemiz
